/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
fun main(){
    println("¡Hola, Kotlin!")
    println("Mi nombre es: Máximo Massut y hoy es 22/04/2025")
    tipos_de_variables()
    calc_area()
    es_negativo_positivo_0(4)
    mostrarNumerosConLoops()
    
}

//Paso 1
fun tipos_de_variables() {
    val nombre: String = "Max"
    val edad: Int = 18
    val altura: Double = 1.75
    val aprobado: Boolean = true
    
    println("Nombre: $nombre")
    println("Edad: $edad")
    println("Altura: $altura")
    println("¿Estoy abprobado?: $aprobado")
}
//Paso 2
fun calc_area(){    
    val base_triangulo: Double=20.3
    val altura_triangulo: Double=60.5

    println("La base del triangulo es:$base_triangulo")
    println("La altura del triangulo es:$altura_triangulo")
    println("Entonces el area del triangulo es:${base_triangulo*altura_triangulo/2}")
}

//Paso3
fun es_negativo_positivo_0(numero:Int):String{
    return when{
        numero > 0 -> "positivo"
        numero < 0 -> "negativo"
        else -> "cero" 
    }
}

//Paso 4
fun mostrarNumerosConLoops() {
    // Usando for}
      println("Usando for:")
    for (i in 1..10 step 1) {
        println(i)
    }
    println("Usando for:")
    for (i in 2..20 step 2) {
        println(i)
    }
    
    // Usando while
    println("\nUsando while:")
    var j = 1
    while (j <= 10){ {
         println(j)
        }
        j++
    }
    var x = 1
    while (x<= 20) {
        if (x % 2 == 0) {
            println(x)
        }
        x++
    }
    
    // Usando do-while
    println("\nUsando do-while:")
    var k = 1 
    do {
        println(k)
        k++
    } while (k <= 10 )

    var y = 1 
    do {
        if (y % 2 == 0) {
            println(y)
        }
        y++
    } while (y <= 20 )
}